//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csla8RestApi.Tests.Models.Complex {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ComplexText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComplexText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Csla8RestApi.Tests.Models.Complex.ComplexText", typeof(ComplexText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The part code cannot exceed {1} characters..
        /// </summary>
        internal static string Part_PartCode_MaxLength {
            get {
                return ResourceManager.GetString("Part_PartCode_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The part code is not unique..
        /// </summary>
        internal static string Part_PartCode_NotUnique {
            get {
                return ResourceManager.GetString("Part_PartCode_NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The part code is required..
        /// </summary>
        internal static string Part_PartCode_Required {
            get {
                return ResourceManager.GetString("Part_PartCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The part name cannot exceed {1} characters..
        /// </summary>
        internal static string Part_PartName_MaxLength {
            get {
                return ResourceManager.GetString("Part_PartName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The part name is required..
        /// </summary>
        internal static string Part_PartName_Required {
            get {
                return ResourceManager.GetString("Part_PartName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product code cannot exceed {1} characters..
        /// </summary>
        internal static string Product_ProductCode_MaxLength {
            get {
                return ResourceManager.GetString("Product_ProductCode_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product code is required..
        /// </summary>
        internal static string Product_ProductCode_Required {
            get {
                return ResourceManager.GetString("Product_ProductCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product name cannot exceed {1} characters..
        /// </summary>
        internal static string Product_ProductName_MaxLength {
            get {
                return ResourceManager.GetString("Product_ProductName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product name is required..
        /// </summary>
        internal static string Product_ProductName_Required {
            get {
                return ResourceManager.GetString("Product_ProductName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product code cannot exceed {1} characters..
        /// </summary>
        internal static string ProductSetItem_ProductCode_MaxLength {
            get {
                return ResourceManager.GetString("ProductSetItem_ProductCode_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product code is required..
        /// </summary>
        internal static string ProductSetItem_ProductCode_Required {
            get {
                return ResourceManager.GetString("ProductSetItem_ProductCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product name cannot exceed {1} characters..
        /// </summary>
        internal static string ProductSetItem_ProductName_MaxLength {
            get {
                return ResourceManager.GetString("ProductSetItem_ProductName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product name is required..
        /// </summary>
        internal static string ProductSetItem_ProductName_Required {
            get {
                return ResourceManager.GetString("ProductSetItem_ProductName_Required", resourceCulture);
            }
        }
    }
}
