version: '3.4'

# Create a volume for the database container to ensure data persists after the container is stopped.
volumes:
  datafiles:

services:
  # Database Service
  csla8modeltemplates.database:
    # Pull the latest PostgreSQL image.
    image: postgres:13.15
    # Map port 5432 on the PostgreSQL container to port 5432 in the host.
    ports:
      - "5432:5432"
    # Specify where the persisted data should be stored.
    volumes:
      - datafiles:/var/lib/postgresql
    restart: always
    # Specify environment variables for PostgreSQL.
    environment: 
      POSTGRES_PASSWORD: L7KFpHIGQm9Hbqm
  # API Service
  csla8modeltemplates.webapi:
    image: ${DOCKER_REGISTRY-}csla8modeltemplateswebapi
    build:
      context: .
      # Use the Docker file in that Directory.
      dockerfile: Csla8ModelTemplates.WebApi/Dockerfile
    # This service depends on the database service specifed above.
    depends_on: 
      - csla8modeltemplates.database
    # Map port 8888 in the API container to port 80 in the Api
    ports:
      - "8080:80"
      - "8081:443"
    restart: always
    # Specify environment variables for the API service.
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORT=8081
    #volumes:
    #  - ${APPDATA}/Microsoft/UserSecrets/:/root/.microsoft/usersecrets
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https/
