// <auto-generated />
using System;
using Csla8ModelTemplates.Dal.Oracle;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Csla8ModelTemplates.Dal.Oracle.Migrations
{
    [DbContext(typeof(OracleContext))]
    [Migration("20240512100508_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Csla8ModelTemplates.Entities.Folder", b =>
                {
                    b.Property<long?>("FolderKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("FolderKey"));

                    b.Property<string>("FolderName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int?>("FolderOrder")
                        .HasColumnType("NUMBER(10)");

                    b.Property<long?>("ParentKey")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("RootKey")
                        .HasColumnType("NUMBER(19)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("FolderKey");

                    b.HasIndex("ParentKey", "FolderOrder");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("Csla8ModelTemplates.Entities.Group", b =>
                {
                    b.Property<long?>("GroupKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("GroupKey"));

                    b.Property<string>("GroupCode")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("GroupKey");

                    b.HasIndex("GroupCode")
                        .IsUnique()
                        .HasFilter("\"GroupCode\" IS NOT NULL");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Csla8ModelTemplates.Entities.GroupPerson", b =>
                {
                    b.Property<long?>("GroupKey")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("PersonKey")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("GroupKey", "PersonKey");

                    b.HasIndex("PersonKey");

                    b.ToTable("GroupPersons");
                });

            modelBuilder.Entity("Csla8ModelTemplates.Entities.Person", b =>
                {
                    b.Property<long?>("PersonKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("PersonKey"));

                    b.Property<string>("PersonCode")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("PersonKey");

                    b.HasIndex("PersonCode")
                        .IsUnique()
                        .HasFilter("\"PersonCode\" IS NOT NULL");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Csla8ModelTemplates.Entities.Player", b =>
                {
                    b.Property<long?>("PlayerKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("PlayerKey"));

                    b.Property<string>("PlayerCode")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("PlayerName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<long?>("TeamKey")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("PlayerKey");

                    b.HasIndex("TeamKey", "PlayerCode")
                        .IsUnique()
                        .HasFilter("\"TeamKey\" IS NOT NULL AND \"PlayerCode\" IS NOT NULL");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Csla8ModelTemplates.Entities.Team", b =>
                {
                    b.Property<long?>("TeamKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("TeamKey"));

                    b.Property<string>("TeamCode")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<Guid?>("TeamGuid")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("TeamKey");

                    b.HasIndex("TeamCode")
                        .IsUnique()
                        .HasFilter("\"TeamCode\" IS NOT NULL");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Csla8ModelTemplates.Entities.Folder", b =>
                {
                    b.HasOne("Csla8ModelTemplates.Entities.Folder", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentKey");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Csla8ModelTemplates.Entities.GroupPerson", b =>
                {
                    b.HasOne("Csla8ModelTemplates.Entities.Group", "Group")
                        .WithMany("Persons")
                        .HasForeignKey("GroupKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Csla8ModelTemplates.Entities.Person", "Person")
                        .WithMany("Groups")
                        .HasForeignKey("PersonKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Csla8ModelTemplates.Entities.Player", b =>
                {
                    b.HasOne("Csla8ModelTemplates.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamKey");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Csla8ModelTemplates.Entities.Folder", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Csla8ModelTemplates.Entities.Group", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("Csla8ModelTemplates.Entities.Person", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Csla8ModelTemplates.Entities.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
