//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csla8ModelTemplates.Models.Simple {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SimpleText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SimpleText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Csla8ModelTemplates.Models.Simple.SimpleText", typeof(SimpleText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new team name is required..
        /// </summary>
        internal static string RenameTeam_TeamName_Required {
            get {
                return ResourceManager.GetString("RenameTeam_TeamName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team code cannot exceed {1} characters..
        /// </summary>
        internal static string SimpleTeam_TeamCode_MaxLength {
            get {
                return ResourceManager.GetString("SimpleTeam_TeamCode_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team code is required..
        /// </summary>
        internal static string SimpleTeam_TeamCode_Required {
            get {
                return ResourceManager.GetString("SimpleTeam_TeamCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team name cannot exceed {1} characters..
        /// </summary>
        internal static string SimpleTeam_TeamName_MaxLength {
            get {
                return ResourceManager.GetString("SimpleTeam_TeamName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team name is required..
        /// </summary>
        internal static string SimpleTeam_TeamName_Required {
            get {
                return ResourceManager.GetString("SimpleTeam_TeamName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team code cannot exceed {1} characters..
        /// </summary>
        internal static string SimpleTeamSetItem_TeamCode_MaxLength {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_TeamCode_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team code is required..
        /// </summary>
        internal static string SimpleTeamSetItem_TeamCode_Required {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_TeamCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team name cannot exceed {1} characters..
        /// </summary>
        internal static string SimpleTeamSetItem_TeamName_MaxLength {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_TeamName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team name is required..
        /// </summary>
        internal static string SimpleTeamSetItem_TeamName_Required {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_TeamName_Required", resourceCulture);
            }
        }
    }
}
