//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csla8ModelTemplates.Dal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SimpleText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SimpleText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Csla8ModelTemplates.Dal.SimpleText", typeof(SimpleText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team has been changed in the meantime..
        /// </summary>
        public static string SimpleTeam_Concurrency {
            get {
                return ResourceManager.GetString("SimpleTeam_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the team because others belong to it..
        /// </summary>
        public static string SimpleTeam_Delete_Others {
            get {
                return ResourceManager.GetString("SimpleTeam_Delete_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the team payers has failed..
        /// </summary>
        public static string SimpleTeam_Delete_Players {
            get {
                return ResourceManager.GetString("SimpleTeam_Delete_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the team has failed..
        /// </summary>
        public static string SimpleTeam_DeleteFailed {
            get {
                return ResourceManager.GetString("SimpleTeam_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new team has failed..
        /// </summary>
        public static string SimpleTeam_InsertFailed {
            get {
                return ResourceManager.GetString("SimpleTeam_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested team has not been found..
        /// </summary>
        public static string SimpleTeam_NotFound {
            get {
                return ResourceManager.GetString("SimpleTeam_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming the team has failed..
        /// </summary>
        public static string SimpleTeam_RenameFailed {
            get {
                return ResourceManager.GetString("SimpleTeam_RenameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team with code {0} already exists..
        /// </summary>
        public static string SimpleTeam_TeamCodeExists {
            get {
                return ResourceManager.GetString("SimpleTeam_TeamCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the team has failed..
        /// </summary>
        public static string SimpleTeam_UpdateFailed {
            get {
                return ResourceManager.GetString("SimpleTeam_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team with code {0} has been changed in the meantime..
        /// </summary>
        public static string SimpleTeamSetItem_Concurrency {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the players of team with code {0} has failed..
        /// </summary>
        public static string SimpleTeamSetItem_Delete_Players {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_Delete_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the team with code {0} has failed..
        /// </summary>
        public static string SimpleTeamSetItem_DeleteFailed {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new team with code {0} has failed..
        /// </summary>
        public static string SimpleTeamSetItem_InsertFailed {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team with code {0} has not been found..
        /// </summary>
        public static string SimpleTeamSetItem_NotFound {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested team has not been found..
        /// </summary>
        public static string SimpleTeamSetItem_NotFoundKey {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_NotFoundKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team with code {0} already exists..
        /// </summary>
        public static string SimpleTeamSetItem_TeamCodeExists {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_TeamCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the team with code {0} has failed..
        /// </summary>
        public static string SimpleTeamSetItem_UpdateFailed {
            get {
                return ResourceManager.GetString("SimpleTeamSetItem_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team has been changed in the meantime..
        /// </summary>
        public static string SimpleTeamUpsert_Concurrency {
            get {
                return ResourceManager.GetString("SimpleTeamUpsert_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the team has failed..
        /// </summary>
        public static string SimpleTeamUpsert_DeleteFailed {
            get {
                return ResourceManager.GetString("SimpleTeamUpsert_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new team has failed..
        /// </summary>
        public static string SimpleTeamUpsert_InsertFailed {
            get {
                return ResourceManager.GetString("SimpleTeamUpsert_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested team has not been found..
        /// </summary>
        public static string SimpleTeamUpsert_NotFound {
            get {
                return ResourceManager.GetString("SimpleTeamUpsert_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team with code {0} already exists..
        /// </summary>
        public static string SimpleTeamUpsert_TeamCodeExists {
            get {
                return ResourceManager.GetString("SimpleTeamUpsert_TeamCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the team has failed..
        /// </summary>
        public static string SimpleTeamUpsert_UpdateFailed {
            get {
                return ResourceManager.GetString("SimpleTeamUpsert_UpdateFailed", resourceCulture);
            }
        }
    }
}
