/****** Object:  Table Folders    Script Date: 5/12/2024 3:37:15 PM ******/
CREATE TABLE Folders(
        FolderKey bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
        ParentKey bigint,
        RootKey bigint,
        FolderOrder int,
        FolderName varchar(100),
        Timestamp datetimeoffset(7) NOT NULL,
 CONSTRAINT PK_Folders PRIMARY KEY CLUSTERED 
(
        FolderKey ASC
)
GO
/****** Object:  Table GroupPersons    Script Date: 5/12/2024 3:37:15 PM ******/
CREATE TABLE GroupPersons(
        GroupKey bigint NOT NULL,
        PersonKey bigint NOT NULL,
 CONSTRAINT PK_GroupPersons PRIMARY KEY CLUSTERED 
(
        GroupKey ASC,
        PersonKey ASC
)
GO
/****** Object:  Table Groups    Script Date: 5/12/2024 3:37:15 PM ******/
CREATE TABLE Groups(
        GroupKey bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
        GroupCode varchar(10),
        GroupName varchar(100),
        Timestamp datetimeoffset(7) NOT NULL,
 CONSTRAINT PK_Groups PRIMARY KEY CLUSTERED 
(
        GroupKey ASC
)
GO
/****** Object:  Table Persons    Script Date: 5/12/2024 3:37:15 PM ******/
CREATE TABLE Persons(
        PersonKey bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
        PersonCode varchar(10),
        PersonName varchar(100),
        Timestamp datetimeoffset(7) NOT NULL,
 CONSTRAINT PK_Persons PRIMARY KEY CLUSTERED 
(
        PersonKey ASC
)
GO
/****** Object:  Table Players    Script Date: 5/12/2024 3:37:15 PM ******/
CREATE TABLE Players(
        PlayerKey bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
        TeamKey bigint,
        PlayerCode varchar(10),
        PlayerName varchar(100),
 CONSTRAINT PK_Players PRIMARY KEY CLUSTERED 
(
        PlayerKey ASC
)
GO
/****** Object:  Table Teams    Script Date: 5/12/2024 3:37:15 PM ******/
CREATE TABLE Teams(
        TeamKey bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
        TeamGuid uniqueidentifier,
        TeamCode varchar(10),
        TeamName varchar(100),
        Timestamp datetimeoffset(7) NOT NULL,
 CONSTRAINT PK_Teams PRIMARY KEY CLUSTERED 
(
        TeamKey ASC
)
GO
/****** Object:  Index IX_Folders_ParentKey_FolderOrder    Script Date: 5/12/2024 3:37:15 PM ******/
CREATE NONCLUSTERED INDEX IX_Folders_ParentKey_FolderOrder ON Folders
(
        ParentKey ASC,
        FolderOrder ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
GO
/****** Object:  Index IX_GroupPersons_PersonKey    Script Date: 5/12/2024 3:37:15 PM ******/
CREATE NONCLUSTERED INDEX IX_GroupPersons_PersonKey ON GroupPersons
(
        PersonKey ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index IX_Groups_GroupCode    Script Date: 5/12/2024 3:37:15 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX IX_Groups_GroupCode ON Groups
(
        GroupCode ASC
)
WHERE (GroupCode IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index IX_Persons_PersonCode    Script Date: 5/12/2024 3:37:15 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX IX_Persons_PersonCode ON Persons
(
        PersonCode ASC
)
WHERE (PersonCode IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index IX_Players_TeamKey_PlayerCode    Script Date: 5/12/2024 3:37:15 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX IX_Players_TeamKey_PlayerCode ON Players
(
        TeamKey ASC,
        PlayerCode ASC
)
WHERE (TeamKey IS NOT NULL AND PlayerCode IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index IX_Teams_TeamCode    Script Date: 5/12/2024 3:37:15 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX IX_Teams_TeamCode ON Teams
(
        TeamCode ASC
)
WHERE (TeamCode IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON PRIMARY
GO
ALTER TABLE Folders  WITH CHECK ADD  CONSTRAINT FK_Folders_Folders_ParentKey FOREIGN KEY(ParentKey)
REFERENCES Folders (FolderKey)
GO
ALTER TABLE Folders CHECK CONSTRAINT FK_Folders_Folders_ParentKey
GO
ALTER TABLE GroupPersons  WITH CHECK ADD  CONSTRAINT FK_GroupPersons_Groups_GroupKey FOREIGN KEY(GroupKey)
REFERENCES Groups (GroupKey)
ON DELETE CASCADE
GO
ALTER TABLE GroupPersons CHECK CONSTRAINT FK_GroupPersons_Groups_GroupKey
GO
ALTER TABLE GroupPersons  WITH CHECK ADD  CONSTRAINT FK_GroupPersons_Persons_PersonKey FOREIGN KEY(PersonKey)
REFERENCES Persons (PersonKey)
ON DELETE CASCADE
GO
ALTER TABLE GroupPersons CHECK CONSTRAINT FK_GroupPersons_Persons_PersonKey
GO
ALTER TABLE Players  WITH CHECK ADD  CONSTRAINT FK_Players_Teams_TeamKey FOREIGN KEY(TeamKey)
REFERENCES Teams (TeamKey)
GO
ALTER TABLE Players CHECK CONSTRAINT FK_Players_Teams_TeamKey
GO
