# Create a volume for the database container to ensure data persists after the container is stopped.
volumes:
  db2-11:

services:
  # Database Service
  csla8mt-db2.database:
    container_name: db2-11
    # Pull the latest DB2 image.
    image: ibmcom/db2:11.5.8.0
    # Map port 50000 on the DB2 container to port 50000 in the host.
    ports:
      - "50000:50000"
    # Specify where the persisted data should be stored.
    volumes:
      - db2-11:/var/lib/db2
    restart: always
    # Specify environment variables for DB2.
    environment: 
      LICENSE: accept
      DB2INST1_PASSWORD: x7DvEZrrNdXf73nt
      DBNAME: Csla8mt
  # API Service
  csla8mt-db2.webapi:
    container_name: csla8mt-db2
    # Pull the latest Web API image.
    image: csla8mt-db2
    build:
      context: .
      # Use the Docker file in that Directory.
      dockerfile: Csla8ModelTemplates.WebApi/Dockerfile
    # This service depends on the database service specifed above.
    depends_on: 
      - csla8mt-db2.database
    # Map port 8888 in the API container to port 80 in the Api
    ports:
      - "8080:80"
      - "8081:443"
    restart: always
    # Specify environment variables for the API service.
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Development.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=kzfoStYF0po3aMV9
      - DB2_CONNSTR=Server=csla8mt-db2.database;Database=Csla8mt;UserID=su;Password=x7DvEZrrNdXf73nt;PersistSecurityInfo=True
      - DB2_CLI_DRIVER_INSTALL_PATH=/app/clidriver
      - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/app/clidriver/lib
      - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/app/clidriver/lib/icc
      - PATH=$PATH:/app/clidriver/bin
    volumes:
      - ./Https:/https/:ro
