version: '3.4'

# Create a volume for the database container to ensure data persists after the container is stopped.
volumes:
  datafiles:

services:
  # Database Service
  csla8modeltemplates.database:
    # Pull the latest DB2 image.
    image: ibmcom/db2:11.5.8.0
    # Map port 50000 on the DB2 container to port 50000 in the host.
    ports:
      - "50000:50000"
    # Specify where the persisted data should be stored.
    volumes:
      - datafiles:/var/lib/db2
    restart: always
    # Specify environment variables for DB2.
    environment: 
      LICENSE: accept
      DB2INST1_PASSWORD: x7DvEZrrNdXf73nt
      DBNAME: Csla8mt
  # API Service
  csla8modeltemplates.webapi:
    image: ${DOCKER_REGISTRY-}csla8modeltemplateswebapi
    build:
      context: .
      # Use the Docker file in that Directory.
      dockerfile: Csla8ModelTemplates.WebApi/Dockerfile
    # This service depends on the database service specifed above.
    depends_on: 
      - csla8modeltemplates.database
    # Map port 8888 in the API container to port 80 in the Api
    ports:
      - "8080:80"
      - "8081:443"
    restart: always
    # Specify environment variables for the API service.
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Development.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=kzfoStYF0po3aMV9
      - DB2_CONNSTR=Server=localhost;Database=Csla8mt;UserID=su;Password=;PersistSecurityInfo=True
    volumes:
      - ${APPDATA}/Certificates:/https/
