# Create a volume for the database container to ensure data persists after the container is stopped.
volumes:
  sqlserver-2022:

services:
  # Database Service
  csla8mt.database:
    container_name: sqlserver-2022
    # Build the container.
    build: ./Setup/SQLServer
    # Map port 1433 on the SQL Server container to port 1433 in the host.
    ports:
      - "1433:1433"
    # Specify where the persisted data should be stored.
    volumes:
      - sqlserver-2022:/var/opt/mssql
    restart: always
  # API Service
  csla8mt.webapi:
    container_name: csla8mt-sqlserver
    # Pull the latest Web API image.
    image: csla8mt.sqlserver
    build:
      context: .
      # Use the Docker file in that Directory.
      dockerfile: Csla8ModelTemplates.WebApi/Dockerfile
    # This service depends on the database service specifed above.
    depends_on: 
      - csla8mt.database
    # Map port 80 in the API container to port 8080 in the host
    # Map port 443 in the API container to port 8081 in the host
    ports:
      - "8080:80"
      - "8081:443"
    restart: always
    # Specify environment variables for the API service.
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Development.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=kzfoStYF0po3aMV9
      - SQLSERVER_CONNSTR=Server=csla8mt.database;Initial Catalog=Csla8mt;User Id=csla8mt;Password=iYJdR7exyFSuA;Trust Server Certificate=True
    volumes:
      - ${APPDATA}/Certificates:/https/
