//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csla8RestApi.Tests.Dal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ComplexText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComplexText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Csla8RestApi.Tests.Dal.ComplexText", typeof(ComplexText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting products has failed..
        /// </summary>
        public static string CountProducts_CountFailed {
            get {
                return ResourceManager.GetString("CountProducts_CountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the part with code {0} has failed..
        /// </summary>
        public static string Part_DeleteFailed {
            get {
                return ResourceManager.GetString("Part_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new part with code {0} has failed..
        /// </summary>
        public static string Part_InsertFailed {
            get {
                return ResourceManager.GetString("Part_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested part has not been found..
        /// </summary>
        public static string Part_NotFound {
            get {
                return ResourceManager.GetString("Part_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part with code {0} already exists..
        /// </summary>
        public static string Part_PartCodeExists {
            get {
                return ResourceManager.GetString("Part_PartCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the part with code {0} has failed..
        /// </summary>
        public static string Part_UpdateFailed {
            get {
                return ResourceManager.GetString("Part_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product has been changed in the meantime..
        /// </summary>
        public static string Product_Concurrency {
            get {
                return ResourceManager.GetString("Product_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete the product because others belong to it..
        /// </summary>
        public static string Product_Delete_Others {
            get {
                return ResourceManager.GetString("Product_Delete_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the product has failed..
        /// </summary>
        public static string Product_DeleteFailed {
            get {
                return ResourceManager.GetString("Product_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new product has failed..
        /// </summary>
        public static string Product_InsertFailed {
            get {
                return ResourceManager.GetString("Product_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested product has not been found..
        /// </summary>
        public static string Product_NotFound {
            get {
                return ResourceManager.GetString("Product_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product with code {0} already exists..
        /// </summary>
        public static string Product_ProductCodeExists {
            get {
                return ResourceManager.GetString("Product_ProductCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the product has failed..
        /// </summary>
        public static string Product_UpdateFailed {
            get {
                return ResourceManager.GetString("Product_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product with code {0} has been changed in the meantime..
        /// </summary>
        public static string ProductSetItem_Concurrency {
            get {
                return ResourceManager.GetString("ProductSetItem_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the product with code {0} has failed..
        /// </summary>
        public static string ProductSetItem_DeleteFailed {
            get {
                return ResourceManager.GetString("ProductSetItem_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new product with code {0} has failed..
        /// </summary>
        public static string ProductSetItem_InsertFailed {
            get {
                return ResourceManager.GetString("ProductSetItem_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product with code {0} has not been found..
        /// </summary>
        public static string ProductSetItem_NotFound {
            get {
                return ResourceManager.GetString("ProductSetItem_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product with code {0} already exists..
        /// </summary>
        public static string ProductSetItem_ProductCodeExists {
            get {
                return ResourceManager.GetString("ProductSetItem_ProductCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the product with code {0} has failed..
        /// </summary>
        public static string ProductSetItem_UpdateFailed {
            get {
                return ResourceManager.GetString("ProductSetItem_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the part with code [ {0} ] {1} has failed..
        /// </summary>
        public static string ProductSetPart_DeleteFailed {
            get {
                return ResourceManager.GetString("ProductSetPart_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new part with code [ {0} ] {1} has failed..
        /// </summary>
        public static string ProductSetPart_InsertFailed {
            get {
                return ResourceManager.GetString("ProductSetPart_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested part with code [ {0} ] {1} has not been found..
        /// </summary>
        public static string ProductSetPart_NotFound {
            get {
                return ResourceManager.GetString("ProductSetPart_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part with code [ {0} ] {1} already exists..
        /// </summary>
        public static string ProductSetPart_PartCodeExists {
            get {
                return ResourceManager.GetString("ProductSetPart_PartCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the part with code [ {0} ] {1} has failed..
        /// </summary>
        public static string ProductSetPart_UpdateFailed {
            get {
                return ResourceManager.GetString("ProductSetPart_UpdateFailed", resourceCulture);
            }
        }
    }
}
